
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 31 19:06:07 CEST 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LPARENT = 7;
  public static final int RPARENT = 8;
  public static final int LBRACKET = 5;
  public static final int CONST = 17;
  public static final int CASE = 29;
  public static final int NOTEQUAL = 39;
  public static final int SEMI = 9;
  public static final int CONTINUE = 25;
  public static final int LESS = 42;
  public static final int FOR = 26;
  public static final int MINUS = 32;
  public static final int CHARACTER = 48;
  public static final int AND = 44;
  public static final int LESSEQUAL = 43;
  public static final int OR = 45;
  public static final int BOOL = 47;
  public static final int COMMA = 10;
  public static final int INC = 36;
  public static final int DIV = 34;
  public static final int PLUS = 31;
  public static final int ASSIGN = 30;
  public static final int IF = 19;
  public static final int DOT = 13;
  public static final int GRATHER = 40;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int EQUAL = 38;
  public static final int RBRACKET = 6;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int MUL = 33;
  public static final int PERCENT = 35;
  public static final int NUMBER = 46;
  public static final int IDENT = 49;
  public static final int BREAK = 14;
  public static final int VOID = 24;
  public static final int SWITCH = 28;
  public static final int FOREACH = 27;
  public static final int COLON = 11;
  public static final int LBRACE = 3;
  public static final int ELSE = 20;
  public static final int ENUM = 16;
  public static final int READ = 23;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int QUESTION = 12;
  public static final int DEC = 37;
  public static final int PRINT = 22;
  public static final int LENGTH = 18;
  public static final int GRATHEREQUAL = 41;
}

